### ISSUE TITLE
Unresponsive Web Server during Data Transfers

### ISSUE THREAD

**Issue by amidsthecode** [Trigus42/alpine-qbittorrentvpn#4]
The qBittorrent webserver goes unresponsive and refuses to connect during active downloads and stays unresponsive till the download is completed and has finished Hash checking. However, the Pi itself is responsive and I am also able to connect to other webservers hosted from other docker containers without any issue. The container may also restart itself during this period of unresponsiveness.
The container during this period never exceeds more than 300 MB of RAM usage.

OS : Raspbian  armv7
Hardware: Raspberry Pi 4 2GB

**Comment by Trigus42** [comment]
I have not been able to reproduce this issue using the same hardware.

Please post the qbittorrent log (under /config/qBittorrent/data/logs/qbittorrent.log) here.
If you are connected to a VPN you should be fine, but still **be careful not to expose any sensitive data**.

This may be a bug in qbittorrent. If you are using the `latest` image which uses qbittorrent version 4.4.0b2, you could try to use the `qbt4.3.7` image instead (which uses the latest stable version of qbittorrent).

**Comment by amidsthecode** [comment]
> This may be a bug in qbittorrent. If you are using the latest image which uses qbittorrent version 4.4.0b2, you could try to use the qbt4.3.7 image instead (which uses the latest stable version of qbittorrent).
I moved to 4.3.7 a few days ago. I was using the latest alpine build prior to that, This behaviour persists in every build I've used.

The one's below are logs of the most recent incident, which had no restarts in the container but the webserver was unresponsive for about 2 hours till the downloads completed.
qbittorrent.log:
`(N) 2021-08-18T20:06:45 - WebAPI login success. IP: ::ffff:192.168.1.14
(N) 2021-08-18T21:40:11 - WebAPI login success. IP: ::ffff:192.168.1.110
(N) 2021-08-18T21:50:25 - 'A 149mb file.zip' reached the maximum ratio you set. Paused.
#this is me adding files represented by numbers to the client
(N) 2021-08-18T22:03:17 - '1' added to download list.
(N) 2021-08-18T22:03:17 - '2' added to download list.
(N) 2021-08-18T22:03:17 - '3' added to download list.
(N) 2021-08-18T22:03:17 - '4' added to download list.
(N) 2021-08-18T22:03:17 - '5' added to download list.
(N) 2021-08-18T22:03:17 - '6' added to download list.
(N) 2021-08-18T22:03:17 - '7' added to download list.
(N) 2021-08-18T22:03:17 - '8' added to download list.
(N) 2021-08-18T22:03:17 - '9' added to download list.
#this is where I lost connection to the webserver and could not log in so I left it alone till the next day
(N) 2021-08-19T09:51:38 - WebAPI login success. IP: ::ffff:192.168.1.110
(N) 2021-08-19T09:51:49 -  'A 149mb file.zip' was removed from the transfer list.
(N) 2021-08-19T13:55:36 - WebAPI login success. IP: ::ffff:192.168.1.110
(N) 2021-08-19T17:58:42 - WebAPI login success. IP: ::ffff:192.168.1.14
(N) 2021-08-19T17:58:48 - WebAPI login success. IP: ::ffff:192.168.1.14
`
docker container logs:
`2021-08-18 18:42:42 [INFO] Unprivileged mode enabled
2021-08-18 18:42:44 [INFO] VPN_ENABLED defined as 'yes'
2021-08-18 18:42:44 [INFO] VPN_TYPE defined as 'wireguard'
2021-08-18 18:42:44 [INFO] WireGuard config file is found at /config/wireguard/wg0.conf
dos2unix: converting file /config/wireguard/wg0.conf to Unix format...
2021-08-18 18:42:44 [INFO] VPN remote line defined as 'VPN endpoint IP:port'
2021-08-18 18:42:44 [INFO] VPN_REMOTE defined as 'VPN endpoint IP'
2021-08-18 18:42:44 [INFO] VPN_PORT defined as 'port'
2021-08-18 18:42:44 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2021-08-18 18:42:44 [INFO] VPN_DEVICE_TYPE set as 'wg0', since WireGuard will always be wg0.
2021-08-18 18:42:44 [INFO] LAN_NETWORK defined as '192.168.1.0/16'
2021-08-18 18:42:44 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2021-08-18 18:42:44 [INFO] Adding 1.1.1.1 to resolv.conf
2021-08-18 18:42:44 [INFO] Adding 8.8.8.8 to resolv.conf
2021-08-18 18:42:44 [INFO] Adding 1.0.0.1 to resolv.conf
2021-08-18 18:42:44 [INFO] Adding 8.8.4.4 to resolv.conf
2021-08-18 18:42:44 [INFO] Starting WireGuard...
Warning: `/config/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.68.206.246/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table "port"
[#] ip -4 rule add not fwmark "port" table "port"
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
2021-08-18 18:42:44 [INFO] Docker network defined as 172.18.0.0/16
2021-08-18 18:42:44 [INFO] Adding 192.168.1.0/16 as route via docker eth0
RTNETLINK answers: Invalid argument
2021-08-18 18:42:44 [INFO] ip route defined as follows...
--------------------
default via 172.18.0.1 dev eth0
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.2
--------------------
iptable_mangle         16384  4
ip_tables              28672  7 iptable_filter,iptable_mangle,iptable_raw
x_tables               32768 18 ipt_REJECT,iptable_filter,xt_connmark,iptable_mangle,xt_comment,iptable_raw,xt_nat,xt_tcpudp,xt_conntrack,xt_MASQUERADE,xt_addrtype,xt_NFQUEUE,xt_set,xt_mark,xt_connbytes,xt_multiport,nft_compat,ip_tables
2021-08-18 18:42:44 [INFO] iptable_mangle support detected, adding fwmark for tables
2021-08-18 18:42:45 [INFO] Adding additional incoming port "Listening Port" for eth0
2021-08-18 18:42:45 [INFO] Adding additional incoming port 8888 for eth0
2021-08-18 18:42:45 [INFO] Adding additional outgoing port "Listening Port" for eth0
2021-08-18 18:42:46 [INFO] Adding additional outgoing port 8888 for eth0
2021-08-18 18:42:46 [INFO] iptables defined as follows...
--------------------
-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-A INPUT -i wg0 -j ACCEPT
-A INPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --sport "port" -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport "Listening Port" -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport "Listening Port" -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8888 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8888 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o wg0 -j ACCEPT
-A OUTPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport "port"-j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport "Listening Port"-j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport "Listening Port" -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8888 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8888 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
--------------------
2021-08-18 18:43:04 [WARNING] ENABLE_SSL is set to , SSL is not enabled. This could cause issues with logging if other apps use the same Cookie name (SID).
2021-08-18 18:43:04 [WARNING] If you manage the SSL config yourself, you can ignore this.
2021-08-18 18:43:04 [INFO] An user with PUID 1000 already exists in /etc/passwd, nothing to do.
2021-08-18 18:43:04 [WARNING] UMASK not defined (via -e UMASK), defaulting to '002'
2021-08-18 18:43:04 [INFO] Starting qBittorrent...
Logging to /config/qBittorrent/data/logs/qbittorrent.log.
2021-08-18 18:43:05 [INFO] qBittorrent PID: 213
2021-08-18 18:43:05 [INFO] HEALTH_CHECK_HOST is not set. For now using default host one.one.one.one
2021-08-18 18:43:05 [INFO] HEALTH_CHECK_SILENT is not set. Because this variable is not set, it will be supressed by default
`
In case you want the compose file:
`  qbittorrent:
    image: trigus42/qbittorrentvpn:qbt4.3.7
    container_name: qbittorrent-wg
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.1.0/16
      - ADDITIONAL_PORTS=56294,8888
      - UNPRIVILEGED=yes
      - HEALTH_CHECK_INTERVAL=1500
    volumes:
      - /path/to/config:/config
      - /path/to/downloads:/downloads
      - /path/to/mount1:/sda1
      - /path/to/mount2:/sdb1    
    dns:
      - 8.8.8.8
    ports:
      - 8888:8080
    env_file:
      - ".env"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always    
`

**Comment by Trigus42** [comment]
I suspect that this is causing your issue:
```
2021-08-18 18:42:44 [INFO] Adding 192.168.1.0/16 as route via docker eth0
RTNETLINK answers: Invalid argument
2021-08-18 18:42:44 [INFO] ip route defined as follows...
--------------------
default via 172.18.0.1 dev eth0
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.2
--------------------
```

You are able to access your web interface anyway because of the fwmark (see [here](https://github.com/Trigus42/alpine-qbittorrentvpn/blob/488bcf37c28c0753bb42092a58b8369b78602ab3/init/iptables.sh#L70-L78) and [here](https://github.com/Trigus42/alpine-qbittorrentvpn/blob/488bcf37c28c0753bb42092a58b8369b78602ab3/init/iptables.sh#L145-L150)):
`
2021-08-18 18:42:44 [INFO] iptable_mangle support detected, adding fwmark for tables
`

I don't know why the fwmark method should fail when transmitting files but I will look into it further. For now you can try fixing your config. `RTNETLINK answers: Invalid argument` is reported because if you specify a CIDR of `16` ip route/rtnetlink expects a zero at the last two bytes of the IP: `192.168.0.0/16` or `192.168.1.0/32`

**Comment by Trigus42** [comment]
I can confirm that, only using the fwmark, the web interface becomes unresponsive when a bunch of torrents are downloading at the same time. It doesn't fail completely, but it gets so slow to the point it causes timeouts. However, using the default method (adding a route to your LAN network via eth0) works flawlessly.
So just fix your config file and you should be fine.

**Comment by Trigus42** [comment]
I don't think we are gonna get more progress on this issue. It also might be resolved already.  
However, feel free to reopen it anytime @amidsthecode or anyone with the same problem.

**Comment by zypherion** [comment]
I am currently having this issue, on 4.4.0. Initiating a download causing intermittent (at best) responsiveness from the web interface, until the download completes.

I've attached the results of the requested TCP dump and output of the ip/iptables commands above from while the issue is occurring. The TCP dump isn't throughout the entire downloading session, but captures the behavior while it's occurring (including a brief moment in the middle where the interface does respond/update before becoming unresponsive again a moment later). If you do need a full download session dumped let me know and I'll grab a smaller download so it's not a crazy long log session.
[qbit_TCPdump.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964336/qbit_TCPdump.txt)
[ip_route_show_table_webui.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964343/ip_route_show_table_webui.txt)
[ip_route_show_table_main.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964344/ip_route_show_table_main.txt)
[ip_rule.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964345/ip_rule.txt)
[iptables_t_L_mangle.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964346/iptables_t_L_mangle.txt)
[iptables_L.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/7964347/iptables_L.txt)

**Comment by Trigus42** [comment]
@zypherion 
You seem to have some issue with your VPN provider:
```
2022-01-28 22:24:54 Restart pause, 160 second(s)
2022-01-28 22:27:34 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2022-01-28 22:27:39 RESOLVE: Cannot resolve host address: zrh-001.vpn.privado.io:1194 (Try again)
2022-01-28 22:27:44 RESOLVE: Cannot resolve host address: zrh-001.vpn.privado.io:1194 (Try again)
2022-01-28 22:27:44 Could not determine IPv4/IPv6 protocol
2022-01-28 22:27:44 SIGUSR1[soft,init_instance] received, process restarting
2022-01-28 22:27:44 Restart pause, 300 second(s)
```

However, from `2022-01-28 22:31:45` to `2022-01-29 18:45:27` in `docker_qbittorrentOVPN.log` your connection probably worked fine. The rest of your logs also seem fine.

Maybe the RPi or rather the SD card or USB bus is too slow and fully utilized by your download. Can you please try to download a torrent, but set the download speed to the minimum (1KB/s)?  
I will try the latest image on my RPi4 as soon as possible.

**Comment by zypherion** [comment]
Thanks for taking a look! I'll dig into my VPN config and see if I can resolve those errors. I suspect the host resolution issue was just momentary DNS failure but the rest can hopefully be cleaned up in it's config.

Interestingly enough, I run my NZBget traffic through the qbit container so it gets piped in/out the VPN as well. During the periods that qbit it unresponsive, NZBget can still download and still responds like there's no issue. So I'm able to pass network traffic through the container while the webUI is unresponsive. I have also removed this config for testing to confirm the qbit container has issues even with the NZBget container handling it's own outbound connection, and even with the NZBget container completely shutdown. The issue persisted. I ran only my qbit container and portainer, just to be safe, but issue persisted.

Overall my pi remains stable and I can reach the other docker containers running on it while the issue is occurring. It's using an M.2 instead of an SD card for it's OS/local storage, but that drive is still shares the USB3 bus. I should be able to grab some disk I/O stats later today (from within the qbit container and the host machine) if that's helpful.

**Comment by zypherion** [comment]
I'm 99% sure this is/was a disk issue on my end... Coupled with a qbit change from upstream?

Seeing the very low overall disk access in the snapshots I remembered that I originally configured qbit to NOT use the storage in the pi at all, but rather it writes directly to a mounted network drive. This includes for incomplete downloads in progress.

At least for now, I've pointed it's incomplete folder to the pi's local m.2 storage. This appears to have resolved the issue. I'm downloading at over 9Mb/s and the web interface is working fine, my VPN itself tops out at 10Mbps-ish. I still don't 100% understand why the previously working config of writing to a network share stopped working in 4.4.0... But lease consider this closed unless you want me to provide any additional info/examples.

**Comment by Trigus42** [comment]
I tried it with my RPi4 and actually encountered the same issue. I was downloading to my SD card. I also tried out version 4.3.9 - same issue. Actually, my whole Pi, while no being totally unresponsive, became very slow and laggy. Limiting the download rate solved the issue. So it seems like the unresponsive web interface is caused by slow storage.
