### ISSUE TITLE
VPN_PORT not found Error with latest version

### ISSUE THREAD

**Issue by crypticviper** [Trigus42/alpine-qbittorrentvpn#56]
Hi,

I get the below error with latest version of docker image (for armv7)

```
2024-01-22 21:16:09 [INFO] Choosen VPN config: 'xxx_all.ovpn'
2024-01-22 21:16:09 [INFO] Using credentials from /config/openvpn/xxx_all_credentials.conf
dos2unix: converting file /config/openvpn/xxx_all.ovpn to Unix format...
2024-01-22 21:16:09 [INFO] VPN remote line defined as 'xxx.xx.xxx.162 1194'
2024-01-22 21:16:09 [INFO] VPN_REMOTE defined as 'xxx.xx.xxx.162'
2024-01-22 21:16:09 [ERROR] VPN_PORT not found in /config/openvpn/xxx_all.ovpn
```

I tried falling back to version qbt4.6.1 and I don't have this issue anymore.

**Comment by acrobatmaxx** [comment]
I have the exact same Issue. I will be following any reply. Thanks for posting!

**Comment by Trigus42** [comment]
This should be the problematic line:
https://github.com/Trigus42/alpine-qbittorrentvpn/blob/3706c033afb33bb7c2bd4e426b20f66ede7ce8e9/rootfs/etc/cont-init.d/20-vpn.sh#L111

Unfortunately I can't reproduce your issue using:
```bash
vpn_remote_line='xxx.xx.xxx.162 1194'
export VPN_PORT=$(echo "${vpn_remote_line}" | grep -o -m 1 -P '^[^#;]*\s\K\d{2,5}(?=\s*$)')
if [[ -n "${VPN_PORT}" ]]; then echo "VPN_PORT defined as '${VPN_PORT}'"; else echo "VPN_PORT not found"; fi
```

Since you redacted your VPNs IP, I'd assume that you don't want to post it publicly. You can encrypt it [here](https://gchq.github.io/CyberChef/#recipe=RSA_Encrypt('-----BEGIN%20PUBLIC%20KEY-----%5CnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6M3nYkDZ4VtIMVRrtzhz%5CnvvC04z%2BMHdKZgTRyG1KlW502gPD7D4rpRHWX4XdcMd/MbQ8yIcj/QUJRhhyQ2mWk%5CnOtts5EZw4s%2BTAOB%2BggmEhbzgtI7L8Vy9iMtKeJjkyTqf3/V5IlVlucoEYLMMil44%5CnoJqYyex/sglR8W3BYln%2BskEFsl2/RVk8ilL0nlBGUzSXY9o5iFGiET8b/B5HfjyU%5Cn541aLSfAXR0TGgf8JwAlyNKg7eWDN6dK%2B9uWq97v6M977pGeOML81zTOkEPpffeD%5CnHi8orhFC0EEMs7OSMCNLhRg0llh8SE%2BBA8ZUU0HEWJ7KJCcFG33YOOgUDSgs9ARW%5CnTwIDAQAB%5Cn-----END%20PUBLIC%20KEY-----','RSA-OAEP','SHA-512')To_Hex('None',0)) (runs locally) or with [this](https://github.com/Trigus42/alpine-qbittorrentvpn/files/14073425/qbtvpn-rsa-pub.txt) public key so only I can see it.


If you are fine with it, can you please use the image `trigus42/qbittorrentvpn:issue_56`, set the environment variable `DEBUG=yes` and post the (encrypted) log? I want to try and reproduce your issue so I need the VPN remote line hexdump. Copying and modifying the VPN remote line might remove whatever causes the issue.

**Comment by crypticviper** [comment]
Here you go. Never used this encryption tool, I had to choose encryption scheme as RAW to get the logs to encrypt properly. Hope that works!

[logs.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/14073609/logs.txt)

**Comment by Trigus42** [comment]
This didn't work. Sorry I didn't think about the fact that the log would actually be too big to encrypt by simply using RSA. 

-------

Too keep things simple, you can just encrypt the log file using a password protected (AES encrypted) 7-zip or zip archive. Choose a secure password, then encrypt the password using the tool at the [link](https://gchq.github.io/CyberChef/#recipe=RSA_Encrypt('-----BEGIN%20PUBLIC%20KEY-----%5CnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6M3nYkDZ4VtIMVRrtzhz%5CnvvC04z%2BMHdKZgTRyG1KlW502gPD7D4rpRHWX4XdcMd/MbQ8yIcj/QUJRhhyQ2mWk%5CnOtts5EZw4s%2BTAOB%2BggmEhbzgtI7L8Vy9iMtKeJjkyTqf3/V5IlVlucoEYLMMil44%5CnoJqYyex/sglR8W3BYln%2BskEFsl2/RVk8ilL0nlBGUzSXY9o5iFGiET8b/B5HfjyU%5Cn541aLSfAXR0TGgf8JwAlyNKg7eWDN6dK%2B9uWq97v6M977pGeOML81zTOkEPpffeD%5CnHi8orhFC0EEMs7OSMCNLhRg0llh8SE%2BBA8ZUU0HEWJ7KJCcFG33YOOgUDSgs9ARW%5CnTwIDAQAB%5Cn-----END%20PUBLIC%20KEY-----','RSA-OAEP','SHA-512')To_Hex('None',0)) I provided. Please do not change any of the parameters of the RSA tool. I don't think it's actually a security problem in this case but generally we are using OAEP padding to improve security.

Please upload both the protected archive and the encrypted password. 

--------

If you'd rather use OpenSSL, you can use the following commands (not bothering with integrity checking here cause it's not really important in our case):

```
# Generate a new AES key
openssl rand -hex 32 > aes.key
# Encrypt file using the AES key (actually using it as a password)
openssl enc -aes-256-ctr -kfile aes.key -pbkdf2 -in YOURLOGFILE -out cipher.bin
# Encrypt AES key with RSA key
openssl pkeyutl -encrypt -pkeyopt rsa_padding_mode:oaep -pkeyopt digest:sha-512 -pubin -inkey rsapubkey.pem -in aes.key -out aes.key.enc
```

Please share the `aes.key.enc` and `cipher.bin` files. Do not share the `aes.key` file.

------

Also sorry for the late reply. I was a little busy this week.

**Comment by crypticviper** [comment]
No problem (regarding the delay). Please find the files attached and let me know if it works.

[_qbittorrent_logs.zip](https://github.com/Trigus42/alpine-qbittorrentvpn/files/14146225/_qbittorrent_logs.zip)
[pass.log](https://github.com/Trigus42/alpine-qbittorrentvpn/files/14146226/pass.log)

**Comment by Trigus42** [comment]
This time it worked. I think I have found your issue too. The problem was that the init script wasn't expecting anything (except spaces) after the VPN port and you had a comment there.
 
Please pull the newest version of the `trigus42/qbittorrentvpn:issue_56` image and let me know if this fixes your problem.

**Comment by crypticviper** [comment]
@Trigus42 it works fine. The comment is from the ovpn files downloaded from the provider. Thanks for looking into it. Please close this once you merge your changes to main.
